server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring:  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example-service
          uri: http://localhost:8093
          predicates:
            - Path=/examples/**
